name: pipelines

on:
  push:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

  security-check:
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Trivy File System Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          output: 'fs-report.json'
          format: 'json'

      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: fs-report.json

      - name: Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
